### PR TITLE
Align with v2 blueprints - #517360

### PR DESCRIPTION
**Pull request by wpschaub**
So, when we trigger a release branch build, the pipelines now looks as follows:
```
CI --> Development --> System Test -+-> Security Automation --> Security Review -+-> Staging --> Production
                                    |                                            |                                   
                                    +--> Quality Assurance Scans ----------------+
```
When we trigger a non-release branch build, it looks as follows:
```
CI --> Development --> System Test -+-> Security Automation
                                    |                                 
                                    +--> Quality Assurance Scans
``` 

You now have the option of running automation for non-release and for release deployments in the renamed Security Automation stage. See security-scans-auto.yml for details.

Also renamed Security Scans to Security Automation and cleanup all templates accordingly.

### CODE REVIEW

**Comment by wpschaub** [comment]
@604kev @danielrbroderick @said-akram approve this PR "after" reviewing and approving the associated common engineering PR.

**Comment by said-akram** [comment]
> @604kev @danielrbroderick @said-akram approve this PR "after" reviewing and approving the associated common engineering PR.

Hi @wpschaub, which PR needs to be approved first? Could you please share the link here?
Thanks

**Comment by wpschaub** [comment]
@said-akram internal PR, which brings us in sync with this open-source PR. Sorry, for you it is only this PR :)

**Review by said-akram — APPROVED** [review]

**Review by danielrbroderick — DISMISSED** [review]

**Review by danielrbroderick — APPROVED** [review]

**Review by 604kev — APPROVED** [review]
Looks good!

**Comment by wpschaub** [comment]
@said-akram any "stop the bus" commands from your side, or can I merge this PR?

**Comment by said-akram** [comment]
> @said-akram any "stop the bus" commands from your side, or can I merge this PR?

I bless this PR in the name of Git 😁

**Pull request merged**
